<?php

function dcx_collections_form_entity_browser_image_browser_form_alter(&$form, $form_state, $id) {
  $form['#attached']['library'][] = 'dcx_collections/dcx_collections';
  $form['widget']['collections'] = [
    '#weight' => -1,
    '#type' => 'details',
    '#collapsible' => TRUE,
    '#title' => Drupal::translation()->translate('Collections'),
  ];
  $collections = \Drupal::service('dcx_integration.client')->getCollections();
  foreach ($collections as $key => $collection) {
    if (empty($collection['documents'])) {
      continue;
    }
    $form['widget']['collections'][$key] = [
      '#type' => 'details',
      '#collapsible' => TRUE,
      '#title' => $collection['name'],
    ];

    $form['widget']['collections'][$key]['list'] = [
      '#theme' => 'item_list',
      '#items' => array_map(function($d) {
        return ['#markup' => "<span class='dcx-preview' data-id='$d'>$d</span>"];
      }, $collection['documents']),

    ];
  }
}
